default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 12345678
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: participatory
  password: 12345678



